# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ninestream' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ninestream
  platform :ios, '9.0'
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Database', '~> 5.3.0'

  target 'ninestreamTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ninestream-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ninestream-tvOS

  target 'ninestream-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
